#!/usr/bin/env bash

set -eu
set -o pipefail

if [[ "${NGROK_AUTOLOAD_CONFIG_DEBUG:-false}" == "true" ]]; then
  set -x
fi

err() {
  echo "$*" >&2
}

die() {
  local line=

  for line in "$@"; do
    err "$line"
  done

  exit 1
}

reverse() {
  if type tac >/dev/null 2>&1; then
    cat - | tac
  else
    cat - | tail -r
  fi
}

get_my_path() {
  local src="${BASH_SOURCE[0]}" temp_dir=''
  while [[ -h "$src" ]]; do
    temp_dir="$(cd -P "$(dirname "$src")" && pwd)"
    src="$(readlink "$src")"

    if [[ ! "$src" =~ ^/.* ]]; then
      src="$temp_dir/$src"
    fi
  done
  cd -P "$(dirname "$src")" && pwd
}

ancestors() {
  local dir=''

  dir="$(pwd)"

  while true; do
    if [[ "$dir" == "$HOME" ]] || [[ "$dir" == "/" ]]; then
      break
    fi

    echo "$dir"
    dir="$(cd "$dir" && cd ../ && pwd)"
  done

  if [[ "${USE_GLOBAL_CONFIG:=true}" != "false" ]]; then
    echo "$HOME/.ngrok2"
  fi
}

get_config_opts() {
  local location='' config_path=''
  local locations=()
  IFS=" " read -r -a locations <<< "$(ancestors | reverse | xargs)"

  for location in "${locations[@]}"; do
    config_path="${location}/ngrok.yml"

    if [[ -f "$config_path" ]]; then
      echo "--config $config_path"
    fi
  done
}

should_load_configs() {
  local -r subcommand="$1"

  case "$subcommand" in
    authtoken|credits|update|version|help|-h)
      return 1
      ;;
    *)
      return 0
      ;;
  esac
}

exec_ngrok_with_configurations() {
  local -r subcommand="$1"
  shift 1
  local options=()
  IFS=" " read -r -a options <<< "$(subcommand::configs-oneline)"
  exec ngrok "$subcommand" "${options[@]}" "$@"
}

exec_ngrok_with_default() {
  local -r subcommand="$1"
  shift 1
  exec ngrok "$subcommand" "$@"
}

is_original_subcommand() {
  declare -F "subcommand::$1" >/dev/null 2>&1
}

subcommand::configs() {
  get_config_opts
}

subcommand::configs-oneline() {
  subcommand::configs | xargs
}

subcommand::update-autoload() {
  if ! type git >/dev/null 2>&1; then
    die "update-autoload cannot be run unless git exists"
  fi

  cd "$(get_my_path)"

  if [[ ! -d ".git" ]]; then
    die "update-autoload can be run only when installed through git clone"
  fi

  git fetch origin release
  git merge --ff origin/release
  echo "Completed update-autoload successfully."
}

if ! type "ngrok" >/dev/null 2>&1; then
  die "ngrok is not found" "please follow https://dashboard.ngrok.com/get-started to install"
fi

SUBCOMMAND="${1:-help}"

if (($# > 0)); then
  shift 1
fi

if is_original_subcommand "$SUBCOMMAND"; then
  "subcommand::$SUBCOMMAND" "$@"
elif [[ "${IGNORE_CONFIG:=false}" != "true" ]] && should_load_configs "$SUBCOMMAND"; then
  exec_ngrok_with_configurations "$SUBCOMMAND" "$@"
else
  exec_ngrok_with_default "$SUBCOMMAND" "$@"
fi
