version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - checkout
      - run:
          name: "Extend PATH"
          command: echo "export PATH="$PWD:$PWD/bin:$PWD/test/bin:$PWD/test/lib/bats/bin:$PATH"" >> "$BASH_ENV"
      - run: git submodule init && git submodule update
      - run: run_test.bash
  lint:
    docker:
      - image: koalaman/shellcheck-alpine
        entrypoint: ''
    steps:
      - checkout
      - run: shellcheck ngrok-autoload-config

workflows:
  version: 2
  feature_branch:
    jobs:
      - test:
          filters:
            branches:
              ignore: /master/
      - lint:
          filters:
            branches:
              ignore: /master/
  on_master:
    jobs:
      - test:
          filters:
            branches:
              only: /master/

