# Orb 'circleci/shellcheck@1.3.4' resolved to 'circleci/shellcheck@1.3.4'
version: 2
jobs:
  jmatsu/bats-test:
    docker:
    - image: circleci/golang:1.12.1
    steps:
    - checkout
    - run:
        command: git submodule init && git submodule update
    - run:
        name: Extend PATH
        command: |
          echo "export BATS_ROOT=$PWD/test/lib/bats" >> "$BASH_ENV"
          echo "export \"PATH=$PWD:$PWD/bin:$PWD/test/bin:$PWD/test/lib/bats/libexec/bats-core:$PATH\"" >> "$BASH_ENV"
    - run:
        command: exec_all_bats.bash
  shellcheck/check:
    docker:
    - image: koalaman/shellcheck-alpine:v0.6.0
    steps:
    - checkout
    - run:
        name: Check Scripts
        command: |
          find '.' -not -path '' -type f -name 'ngrok-autoload-config' | tee /dev/tty | xargs shellcheck --external-sources
workflows:
  feature_branch:
    jobs:
    - jmatsu/bats-test:
        filters:
          branches:
            ignore: /master/
    - shellcheck/check:
        filters:
          branches:
            ignore: /master/
  on_master:
    jobs:
    - jmatsu/bats-test:
        filters:
          branches:
            only: /master/
  version: 2

# Original config.yml file:
# version: 2.1
# 
# orbs:
#   shellcheck: circleci/shellcheck@1.3.4
#   jmatsu:
#     executors:
#       default-executor:
#         docker:
#           - image: circleci/golang:1.12.1
#     commands:
#       init-git-submodules:
#         steps:
#           - run: git submodule init && git submodule update
#       extend_path:
#         steps:
#           - run:
#               name: \"Extend PATH\"
#               command: |
#                 echo \"export BATS_ROOT=$PWD/test/lib/bats\" >> \"$BASH_ENV\"
#                 echo \"export \\\"PATH=$PWD:$PWD/bin:$PWD/test/bin:$PWD/test/lib/bats/libexec/bats-core:$PATH\\\"\" >> \"$BASH_ENV\"
#     jobs:
#       bats-test:
#         executor: default-executor
#         steps:
#           - checkout
#           - init-git-submodules
#           - extend_path
#           - run: exec_all_bats.bash
# 
# filters:
#   only_master: &only_master
#     filters:
#       branches:
#         only: /master/
#   ignore_master: &ignore_master
#     filters:
#       branches:
#         ignore: /master/
# 
# workflows:
#   feature_branch:
#     jobs:
#       - jmatsu/bats-test:
#           <<: *ignore_master
#       - shellcheck/check:
#           pattern: ngrok-autoload-config
#           <<: *ignore_master
#   on_master:
#     jobs:
#       - jmatsu/bats-test:
#           <<: *only_master