version: 2
jobs:
  lint:
    docker:
      - image: bats/bats:latest
    steps:
      - checkout
      - run:
          name: "Extend PATH"
          command: echo "export PATH="$PWD:$PWD/bin:$PWD/test/bin:$PATH"" >> "$BASH_ENV"
      - run: git submodule init
      - run: run_test.bash
  test:
    docker:
      - image: koalaman/shellcheck-alpine
        entrypoint: ''
    steps:
      - checkout
      - run: git submodule init
      - run: shellcheck ngrok-autoload-config

workflows:
  version: 2
  feature_branch:
    jobs:
      - test
      - lint
    filters:
      branches:
        ignore: /master/
  on_master:
    jobs:
      - test
    filters:
      branches:
        only: /master/

